"use client";

import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Provider } from "react-redux";

import { persistor, store } from "@/store/store";
import { PersistGate } from "redux-persist/integration/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            {/* <QueryClientProvider client={client}> */}
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem={false}
              // disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
            {/* </QueryClientProvider> */}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
