'use client';

interface Props {
  data: {
    todayHabitDone: number;
    totalHabits: number;
    bestHabitStreak: number;
    activeDays: number;
    totalHabitCompletions: number;
    completionRate: number;
  };
  theme: boolean;
}

export function ExportStatsCard({ data, theme }: Props) {
  const bg = theme ? "#1a1a1a" : "#0b1f17";
  const border = theme ? "#2d2d2d" : "#123d2c";
  const text = "#ffffff";
  const muted = theme ? "#a1a1aa" : "#86efac";

  return (
    <div
      id="export-card"
      style={{
        width: 900,
        height: 900,
        background: bg,
        border: `2px solid ${border}`,
        borderRadius: 32,
        padding: 40,
        color: text,
        fontFamily: "system-ui",
        display: 'flex',
        flexDirection: "column",
        justifyContent: "space-between",
      }}
    >
      {/* HEADER */}
      <div>
        <div style={{ fontSize: 14, opacity: 0.6, letterSpacing: 2 }}>
          TRACKER REPORT
        </div>

        <div style={{ fontSize: 34, fontWeight: 800, marginTop: 10 }}>
          🧠 Daily System
        </div>

        <div style={{ fontSize: 14, color: muted, marginTop: 6 }}>
          Habits • Discipline • Progress
        </div>
      </div>

      {/* MAIN STATS */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr 1fr",
          gap: 20,
        }}
      >
        <Stat label="Today habits" value={`${data.todayHabitDone}/${data.totalHabits}`} />
        <Stat label="Streak" value={data.bestHabitStreak} />
        <Stat label="Active days" value={data.activeDays} />
        <Stat label="Completed" value={data.totalHabitCompletions} />
      </div>

      {/* FOOTER */}
      <div>
        <div style={{ fontSize: 18, fontWeight: 700 }}>
          {data.completionRate}% completion today
        </div>

        <div style={{ fontSize: 12, opacity: 0.6, marginTop: 6 }}>
          Generated by your tracker system
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value }: any) {
  return (
    <div
      style={{
        padding: 20,
        borderRadius: 20,
        border: "1px solid rgba(255,255,255,0.08)",
        background: "rgba(255,255,255,0.03)",
      }}
    >
      <div style={{ fontSize: 12, opacity: 0.6 }}>{label}</div>
      <div style={{ fontSize: 26, fontWeight: 800, marginTop: 6 }}>
        {value}
      </div>
    </div>
  );
}